### ISSUE TITLE
Frontend document code

### ISSUE THREAD

**Issue by JdPerumal** [COS301-SE-2021/Harmony#25]

**Comment by Tiashka** [comment]
chose bit
https://harmony-docs.bit.dev/getting-started/initializing-workspace

**Comment by Tiashka** [comment]
https://dev.to/paulasantamaria/document-your-javascript-code-with-jsdoc-2fbf
https://jsdoc.app/about-getting-started.html#generating-a-website

unchose bit as it was too difficult to use, jsdoc is much easier to use and more lightweight

**Comment by Tiashka** [comment]
documented the web app with jsdoc
