### ISSUE TITLE
Task 1.4 - Implementation of UI on React Native -  Home Screen

### ISSUE THREAD

**Issue by ASacoor** [COS301-SE-2021/Harmony#49]
Deadline : 01/07/2021 - Thursday

**Comment by Tiashka** [comment]
Finished UI  for home screen including API call

**Comment by ASacoor** [comment]
01/07/2021 - Partially Completed
- Overall base layout  was completed

**Comment by Tiashka** [comment]
- [ ] remove border from cards
- [ ] remove stars 
- [ ] fill images for the cards
- [ ] add in search bar
- [ ] fix title bar to have dynamic title
- [ ] add in button feedback

review: 15/07
deadline: 17/07
final deadline: 20/07

**Comment by JdPerumal** [comment]
create the mock responses for the requests

**Comment by Tiashka** [comment]
completed the dynamic title,
removed the stars
removed the borders
added carousel tags
restructured the home page file

**Comment by Tiashka** [comment]
- [ ] fill images for the cards
- [ ] add in search icon
- [ ] add in button feedback
- [ ] do the mock response
- [ ] center the food names

review: 21/07
final: 22/07

**Comment by Tiashka** [comment]
added the search icon + fixed the header 
20/07

**Comment by Tiashka** [comment]
filled the images, centered the foodItem names
21/7
*had to remove the shadow as it was causing padding issues for the images

**Comment by Tiashka** [comment]
up+down to be more spaced between them, to the right
bigger text and more space between filter + search buttons
heart in pink 
remove weird grey bar by location

create mock response : addToFavouriteDetails [ (heart/hear-outlined),  (pink/black)   ]
centering text:
one large view
      two views 
           food view -image + text        set width to image and center alin
           drink view - image + text 
 

reduce tag size
location = lighter blue put space bet icon + text
add a box on the right with distance eg 3km, 15km etc
remove add to fav confirmation

move scroll bar to far right

**Comment by ASacoor** [comment]
HomeScreen Update Deadline not  : 25/07/2021 3pm
New Deadline: 25/07/2021 7:30 pm

**Comment by Tiashka** [comment]
25/7
- aligned text

**Comment by Tiashka** [comment]
post meeting notes

- [ ] left align distance to below address and center to icon
- [ ] round image corners
- [ ] feedback on up+downvotes
- [ ] change heart to a hexa pink
- [ ] add dividers in the card
- [ ] make the fooditem names bold
- [ ] vertical align the trending word
- [ ] remove description 
- [ ] add pull down to refresh

**Comment by Tiashka** [comment]
completed tasks by 26/07

**Comment by Tiashka** [comment]
comments from meeting

- [ ] status bar in heading
- [ ] swap up and down
- [ ] check and uncheck of icons
- [ ] lower the location icon
- [ ] search is an api call

**Comment by ASacoor** [comment]
26/07/2021 - HomeScreen Cards
90% Completed, waiting for Backend API

**Comment by JdPerumal** [comment]
Add shadows to cards once all-important functionality has been completed

**Comment by Tiashka** [comment]
Update: came back to home screen to proof the code and increase readability.

review: 3/07
due: 04/07

**Comment by JdPerumal** [comment]
Re-implemented filterModal as a re-usable component.
Implemented tags to be more re-usable using iteration.

**Comment by Tiashka** [comment]
externalized the cards to be a component along with the location and iconbar.
encountered a problem with getting the filters to clear as theyre now externally controlled

**Comment by Tiashka** [comment]
ran into a few issues, the states not saving on reopen of the modal,
looking into Context (https://reactjs.org/docs/context.html) and redux (https://redux.js.org/) to see which would be best suitable to hold value externally
![image](https://user-images.githubusercontent.com/74132226/128219359-34b2f5a6-e247-492c-b102-7db0004f4cc6.png)

**Comment by Tiashka** [comment]
Resources
https://redux.js.org/tutorials/fundamentals/part-1-overview

**Comment by Tiashka** [comment]
completed the filters and clear all, they save their state in a redux store when closed. waiting for @MohammedCarrim to finish deploying the home screen APIs and filter APIs

**Comment by Tiashka** [comment]
*redid the entire redux to take three seperate tags and all the reducer actions
*fixed the modal bug, if you want a value greater than 100 you may type it without errors
*implemented the lacation to now refresh the page when its loaded
       - because its an asynchronous call javascript does not wait for it to finish before continuing, i have tried getting to to not be asynchronous but i get an undefined object error, so now the page just refreshes when the location is loaded
       - we can talk more about this should anyone have another idea


=>filters all work
=>upvoting and downvoting + favouriting all works
=>it remembers which youve already interacted with
