### ISSUE TITLE
Task 1.7 - Implementation of UI on React Native - Filters for Home Screen

### ISSUE THREAD

**Issue by ASacoor** [COS301-SE-2021/Harmony#52]
Deadline : 04/06/2021 - Sunday

**Comment by Tiashka** [comment]
Filter implementation was completed, now to add in the decided filters
![image](https://user-images.githubusercontent.com/74132226/126911870-4ab7cc26-a698-4ad8-9f7c-0b01cbe41827.png)


deadline
Review : 27/07
final : 28/08

**Comment by Tiashka** [comment]
27/07
filled in all the filters so far, started styling all the pickers

**Comment by Tiashka** [comment]
28/08
Finished styling waiting for review

**Comment by Tiashka** [comment]
- [ ] copy modal from pairing results feedback modal pairing results screen
- [ ] add feedback to filter button
- [ ] add filter pairing title
- [ ] add x button to do no change
- [ ] apply button calls the api
- [ ] slider circle should get bigger on touch
- [ ] remove distance result put the number under the slider
- [ ] option to type in distance or drag the slider
- [ ] put borders around filters
- [ ] 
![image](https://user-images.githubusercontent.com/74132226/127314985-0af36a05-e566-4755-a610-cdd102370f7e.png)

**Comment by Tiashka** [comment]
post tags meeting notes:

- [ ] implement option to select multiple tags and filter by it

**Comment by Tiashka** [comment]
note to self: when clicking out should restore all tags to grey

**Comment by Tiashka** [comment]
meeting notes:

- [ ] move trending name to center
- [ ] pad default value
- [ ] try putting heading
- [ ] make apply button wider
- [ ] change text to white
- [ ] icon next to the name

**Comment by ASacoor** [comment]
Task is now completed - 9 am , 31/07/2021 

Unable to have meeting 
This has been reviewed with a screenshot and the task is now closed
Please continue to the next task
