### ISSUE TITLE
Image Recognition Implementation - returning image responses food and drinks

### ISSUE THREAD

**Issue by MohammedCarrim** [COS301-SE-2021/Harmony#79]
Deadline - 10/07/2021

**Comment by MohammedCarrim** [comment]
Base64 image request is acceptable, image converted to binary then passed to the azure api

**Comment by Keval157** [comment]
Response is created, just need to add image to response

**Comment by Keval157** [comment]
Full response with image data is completed. Need confirmation on whether the response is correctly formatted before closing the issue.

**Comment by MohammedCarrim** [comment]
Response has been completed and formatted accordingly

**Comment by MohammedCarrim** [comment]
use case linked and works with frontend, full implementation complete
