### ISSUE TITLE
create mock response

### ISSUE THREAD

**Issue by Tiashka** [COS301-SE-2021/Harmony#95]
create the mock responses for the requests

**Comment by Tiashka** [comment]
fix cards:

- [ ] add feedback for buttons
- [ ] add dynamic top bar
- [ ] remove card borders
- [ ] remove stars
- [ ] add search design
- [ ] use mock data 
- [ ] convert tags into carousel

review session: 15/07
new deadline : 17/07

**Comment by JdPerumal** [comment]
Closed and added to an existing issue:
Task 1.4 - Implementation of UI on React Native - Home Screen #49
